[package]
name = "vslam_frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vslam_core={path="../vslam_core"}
image="*"
nalgebra="*"
