[package]
name = "vslam_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "*"
imageproc="*"
nalgebra="*"
vslam_core={path="../vslam_core"}
vslam_frontend={path="../vslam_frontend"}
